// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQZ1Y9EQlN0ETqKhuC31JySFBSCF8DNM',
    appId: '1:402758474947:web:deac13b596cf52cf6d1676',
    messagingSenderId: '402758474947',
    projectId: 'ves-canteen',
    authDomain: 'ves-canteen.firebaseapp.com',
    storageBucket: 'ves-canteen.appspot.com',
    measurementId: 'G-NELFKS1TYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADJQY12Sw1lPEbUuXRM2IqsInQKg_-HMY',
    appId: '1:402758474947:android:af3d2b172bfebd556d1676',
    messagingSenderId: '402758474947',
    projectId: 'ves-canteen',
    storageBucket: 'ves-canteen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHodQ68sJ_ELVfIBdCjjB-0NPpSzhhJ1g',
    appId: '1:402758474947:ios:6d592a9c793366ae6d1676',
    messagingSenderId: '402758474947',
    projectId: 'ves-canteen',
    storageBucket: 'ves-canteen.appspot.com',
    iosClientId: '402758474947-g1j5trb0kii0ip1conqqmhuuhnsirnad.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHodQ68sJ_ELVfIBdCjjB-0NPpSzhhJ1g',
    appId: '1:402758474947:ios:c97cf5866e356f2b6d1676',
    messagingSenderId: '402758474947',
    projectId: 'ves-canteen',
    storageBucket: 'ves-canteen.appspot.com',
    iosClientId: '402758474947-mht6i7nceahn79iu41ms1ibdsiq2sjnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteen.RunnerTests',
  );
}
